import angular from 'angular-eslint';
import tseslint from 'typescript-eslint';
import jig from '../tools/lint/index.ts';

// The frontend gate. eslint-disable comments are switched off wholesale via
// noInlineConfig, because a rule with a suppression dial is not a rule — the same
// standard ADR 0009 holds the Roslyn analyzers to. There is no escape hatch by
// design.
//
// libs/** is ignored: it is generated by npm run ui:style and must never be
// hand-edited (ADR 0010).
//
// The ignores below are rooted at "frontend/", not at this config file's own
// directory. ESLint 9 resolves an ignores glob relative to the config's
// basePath, and basePath is the directory containing the config file ONLY when
// ESLint discovers the config on its own; the `lint` script passes --config
// explicitly (required so a repo-root `npm run lint` finds this file at all),
// and passing --config pins basePath to the CLI's cwd, which is the repo root.
// Root-relative patterns are therefore the only ones that match here.
export default [
  {
    ignores: [
      'frontend/dist/**',
      'frontend/.angular/**',
      'frontend/node_modules/**',
      'frontend/coverage/**',
      'frontend/libs/**',
    ],
  },
  {
    files: ['**/*.ts'],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: { project: false },
    },
    processor: angular.processInlineTemplates,
    linterOptions: { noInlineConfig: true },
  },
  {
    files: ['**/*.html'],
    languageOptions: { parser: angular.templateParser },
    plugins: { jig },
    linterOptions: { noInlineConfig: true },
    rules: {
      'jig/no-literal-spacing': 'error',
    },
  },
];
