// GENERATED by tools/showcase-api — do not edit. Run `npm run showcase:api`.
import type { ApiClass } from './component-api.types';

export const COMPONENT_API: Readonly<Record<string, readonly ApiClass[]>> = {
  "accordion": [
    {
      "className": "HlmAccordion",
      "selector": "[hlmAccordion], hlm-accordion",
      "members": []
    },
    {
      "className": "HlmAccordionContent",
      "selector": "hlm-accordion-content",
      "members": []
    },
    {
      "className": "HlmAccordionItem",
      "selector": "[hlmAccordionItem],hlm-accordion-item",
      "members": []
    },
    {
      "className": "HlmAccordionTrigger",
      "selector": "hlm-accordion-trigger",
      "members": [
        {
          "kind": "input",
          "name": "triggerClass",
          "type": "ClassValue",
          "required": false
        }
      ]
    }
  ],
  "alert": [
    {
      "className": "HlmAlert",
      "selector": "hlm-alert,[hlmAlert]",
      "members": [
        {
          "kind": "input",
          "name": "variant",
          "type": "AlertVariants['variant']",
          "required": false
        }
      ]
    },
    {
      "className": "HlmAlertAction",
      "selector": "[hlmAlertAction]",
      "members": []
    },
    {
      "className": "HlmAlertDescription",
      "selector": "[hlmAlertDescription]",
      "members": []
    },
    {
      "className": "HlmAlertTitle",
      "selector": "[hlmAlertTitle]",
      "members": []
    }
  ],
  "alert-dialog": [
    {
      "className": "HlmAlertDialog",
      "selector": "hlm-alert-dialog",
      "members": []
    },
    {
      "className": "HlmAlertDialogAction",
      "selector": "button[hlmAlertDialogAction]",
      "members": [
        {
          "kind": "input",
          "name": "type",
          "type": "'button' | 'submit' | 'reset'",
          "required": false
        }
      ]
    },
    {
      "className": "HlmAlertDialogCancel",
      "selector": "button[hlmAlertDialogCancel]",
      "members": [
        {
          "kind": "input",
          "name": "type",
          "type": "'button' | 'submit' | 'reset'",
          "required": false
        }
      ]
    },
    {
      "className": "HlmAlertDialogContent",
      "selector": "[hlmAlertDialogContent],hlm-alert-dialog-content",
      "members": [
        {
          "kind": "input",
          "name": "size",
          "type": "'sm' | 'default'",
          "required": false
        }
      ]
    },
    {
      "className": "HlmAlertDialogDescription",
      "selector": "[hlmAlertDialogDescription]",
      "members": []
    },
    {
      "className": "HlmAlertDialogFooter",
      "selector": "[hlmAlertDialogFooter],hlm-alert-dialog-footer",
      "members": []
    },
    {
      "className": "HlmAlertDialogHeader",
      "selector": "[hlmAlertDialogHeader],hlm-alert-dialog-header",
      "members": []
    },
    {
      "className": "HlmAlertDialogMedia",
      "selector": "[hlmAlertDialogMedia],hlm-alert-dialog-media",
      "members": []
    },
    {
      "className": "HlmAlertDialogOverlay",
      "selector": "[hlmAlertDialogOverlay],hlm-alert-dialog-overlay",
      "members": [
        {
          "kind": "input",
          "name": "class",
          "type": "ClassValue",
          "required": false
        }
      ]
    },
    {
      "className": "HlmAlertDialogPortal",
      "selector": "[hlmAlertDialogPortal]",
      "members": []
    },
    {
      "className": "HlmAlertDialogTitle",
      "selector": "[hlmAlertDialogTitle]",
      "members": []
    },
    {
      "className": "HlmAlertDialogTrigger",
      "selector": "button[hlmAlertDialogTrigger],button[hlmAlertDialogTriggerFor]",
      "members": []
    }
  ],
  "aspect-ratio": [
    {
      "className": "HlmAspectRatio",
      "selector": "[hlmAspectRatio]",
      "members": [
        {
          "kind": "input",
          "name": "hlmAspectRatio",
          "type": "number, NumberInput",
          "required": false
        }
      ]
    }
  ],
  "autocomplete": [
    {
      "className": "HlmAutocomplete",
      "selector": "[hlmAutocomplete],hlm-autocomplete",
      "members": []
    },
    {
      "className": "HlmAutocompleteContent",
      "selector": "[hlmAutocompleteContent],hlm-autocomplete-content",
      "members": []
    },
    {
      "className": "HlmAutocompleteEmpty",
      "selector": "[hlmAutocompleteEmpty],hlm-autocomplete-empty",
      "members": []
    },
    {
      "className": "HlmAutocompleteGroup",
      "selector": "[hlmAutocompleteGroup]",
      "members": []
    },
    {
      "className": "HlmAutocompleteInput",
      "selector": "hlm-autocomplete-input",
      "members": [
        {
          "kind": "input",
          "name": "inputId",
          "type": "string",
          "required": false
        },
        {
          "kind": "input",
          "name": "placeholder",
          "type": "string",
          "required": false
        },
        {
          "kind": "input",
          "name": "showSearch",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "showClear",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "forceInvalid",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "aria-invalid",
          "type": "boolean | undefined, BooleanInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmAutocompleteItem",
      "selector": "hlm-autocomplete-item",
      "members": []
    },
    {
      "className": "HlmAutocompleteLabel",
      "selector": "[hlmAutocompleteLabel]",
      "members": []
    },
    {
      "className": "HlmAutocompleteList",
      "selector": "[hlmAutocompleteList]",
      "members": []
    },
    {
      "className": "HlmAutocompletePortal",
      "selector": "[hlmAutocompletePortal]",
      "members": []
    },
    {
      "className": "HlmAutocompleteSearch",
      "selector": "[hlmAutocompleteSearch],hlm-autocomplete-search",
      "members": []
    },
    {
      "className": "HlmAutocompleteSeparator",
      "selector": "[hlmAutocompleteSeparator]",
      "members": []
    },
    {
      "className": "HlmAutocompleteStatus",
      "selector": "[hlmAutocompleteStatus],hlm-autocomplete-status",
      "members": []
    }
  ],
  "avatar": [
    {
      "className": "HlmAvatar",
      "selector": "hlm-avatar",
      "members": [
        {
          "kind": "input",
          "name": "size",
          "type": "'default' | 'sm' | 'lg'",
          "required": false
        }
      ]
    },
    {
      "className": "HlmAvatarBadge",
      "selector": "[hlmAvatarBadge],hlm-avatar-badge",
      "members": []
    },
    {
      "className": "HlmAvatarFallback",
      "selector": "[hlmAvatarFallback]",
      "members": []
    },
    {
      "className": "HlmAvatarGroup",
      "selector": "[hlmAvatarGroup],hlm-avatar-group",
      "members": []
    },
    {
      "className": "HlmAvatarGroupCount",
      "selector": "[hlmAvatarGroupCount],hlm-avatar-group-count",
      "members": []
    },
    {
      "className": "HlmAvatarImage",
      "selector": "img[hlmAvatarImage]",
      "members": []
    }
  ],
  "badge": [
    {
      "className": "HlmBadge",
      "selector": "[hlmBadge],hlm-badge",
      "members": [
        {
          "kind": "input",
          "name": "variant",
          "type": "BadgeVariants['variant']",
          "required": false
        }
      ]
    }
  ],
  "breadcrumb": [
    {
      "className": "HlmBreadcrumb",
      "selector": "[hlmBreadcrumb]",
      "members": [
        {
          "kind": "input",
          "name": "aria-label",
          "type": "string",
          "required": false
        }
      ]
    },
    {
      "className": "HlmBreadcrumbEllipsis",
      "selector": "hlm-breadcrumb-ellipsis",
      "members": [
        {
          "kind": "input",
          "name": "srOnlyText",
          "type": "string",
          "required": false
        }
      ]
    },
    {
      "className": "HlmBreadcrumbItem",
      "selector": "[hlmBreadcrumbItem]",
      "members": []
    },
    {
      "className": "HlmBreadcrumbLink",
      "selector": "[hlmBreadcrumbLink]",
      "members": [
        {
          "kind": "input",
          "name": "link",
          "type": "RouterLink['routerLink']",
          "required": false
        }
      ]
    },
    {
      "className": "HlmBreadcrumbList",
      "selector": "[hlmBreadcrumbList]",
      "members": []
    },
    {
      "className": "HlmBreadcrumbPage",
      "selector": "[hlmBreadcrumbPage]",
      "members": []
    },
    {
      "className": "HlmBreadcrumbSeparator",
      "selector": "[hlmBreadcrumbSeparator]",
      "members": []
    }
  ],
  "button": [
    {
      "className": "HlmButton",
      "selector": "button[hlmBtn], a[hlmBtn]",
      "members": [
        {
          "kind": "input",
          "name": "variant",
          "type": "ButtonVariants['variant']",
          "required": false
        },
        {
          "kind": "input",
          "name": "size",
          "type": "ButtonVariants['size']",
          "required": false
        }
      ]
    }
  ],
  "button-group": [
    {
      "className": "HlmButtonGroup",
      "selector": "[hlmButtonGroup],hlm-button-group",
      "members": [
        {
          "kind": "input",
          "name": "orientation",
          "type": "'horizontal' | 'vertical'",
          "required": false
        }
      ]
    },
    {
      "className": "HlmButtonGroupSeparator",
      "selector": "[hlmButtonGroupSeparator],hlm-button-group-separator",
      "members": []
    },
    {
      "className": "HlmButtonGroupText",
      "selector": "[hlmButtonGroupText],hlm-button-group-text",
      "members": []
    }
  ],
  "calendar": [
    {
      "className": "HlmCalendar",
      "selector": "hlm-calendar",
      "members": [
        {
          "kind": "input",
          "name": "captionLayout",
          "type": "'dropdown' | 'label' | 'dropdown-months' | 'dropdown-years'",
          "required": false
        }
      ]
    },
    {
      "className": "HlmCalendarMulti",
      "selector": "hlm-calendar-multi",
      "members": [
        {
          "kind": "input",
          "name": "captionLayout",
          "type": "'dropdown' | 'label' | 'dropdown-months' | 'dropdown-years'",
          "required": false
        }
      ]
    },
    {
      "className": "HlmCalendarRange",
      "selector": "hlm-calendar-range",
      "members": [
        {
          "kind": "input",
          "name": "captionLayout",
          "type": "'dropdown' | 'label' | 'dropdown-months' | 'dropdown-years'",
          "required": false
        }
      ]
    }
  ],
  "card": [
    {
      "className": "HlmCard",
      "selector": "[hlmCard],hlm-card",
      "members": [
        {
          "kind": "input",
          "name": "size",
          "type": "HlmCardConfig['size']",
          "required": false
        }
      ]
    },
    {
      "className": "HlmCardAction",
      "selector": "[hlmCardAction]",
      "members": []
    },
    {
      "className": "HlmCardContent",
      "selector": "[hlmCardContent]",
      "members": []
    },
    {
      "className": "HlmCardDescription",
      "selector": "[hlmCardDescription]",
      "members": []
    },
    {
      "className": "HlmCardFooter",
      "selector": "[hlmCardFooter],hlm-card-footer",
      "members": []
    },
    {
      "className": "HlmCardHeader",
      "selector": "[hlmCardHeader],hlm-card-header",
      "members": []
    },
    {
      "className": "HlmCardTitle",
      "selector": "[hlmCardTitle]",
      "members": []
    }
  ],
  "carousel": [
    {
      "className": "HlmCarousel",
      "selector": "hlm-carousel",
      "members": [
        {
          "kind": "input",
          "name": "orientation",
          "type": "'horizontal' | 'vertical'",
          "required": false
        }
      ]
    },
    {
      "className": "HlmCarouselContent",
      "selector": "[hlmCarouselContent],hlm-carousel-content",
      "members": []
    },
    {
      "className": "HlmCarouselItem",
      "selector": "[hlmCarouselItem],hlm-carousel-item",
      "members": []
    },
    {
      "className": "HlmCarouselNext",
      "selector": "button[hlm-carousel-next], button[hlmCarouselNext]",
      "members": []
    },
    {
      "className": "HlmCarouselPrevious",
      "selector": "button[hlm-carousel-previous], button[hlmCarouselPrevious]",
      "members": []
    },
    {
      "className": "HlmCarouselSlideDisplay",
      "selector": "hlm-carousel-slide-display",
      "members": [
        {
          "kind": "input",
          "name": "slideClass",
          "type": "ClassValue",
          "required": false
        },
        {
          "kind": "input",
          "name": "label",
          "type": "string",
          "required": false
        }
      ]
    }
  ],
  "checkbox": [
    {
      "className": "HlmCheckbox",
      "selector": "hlm-checkbox",
      "members": [
        {
          "kind": "input",
          "name": "class",
          "type": "ClassValue",
          "required": false
        },
        {
          "kind": "input",
          "name": "inputId",
          "type": "string | null",
          "required": false
        },
        {
          "kind": "input",
          "name": "aria-label",
          "type": "string | null",
          "required": false
        },
        {
          "kind": "input",
          "name": "aria-labelledby",
          "type": "string | null",
          "required": false
        },
        {
          "kind": "input",
          "name": "aria-describedby",
          "type": "string | null",
          "required": false
        },
        {
          "kind": "input",
          "name": "checked",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "output",
          "name": "checkedChange",
          "type": "boolean",
          "required": false
        },
        {
          "kind": "model",
          "name": "indeterminate",
          "type": "boolean",
          "required": false
        },
        {
          "kind": "input",
          "name": "name",
          "type": "string | null",
          "required": false
        },
        {
          "kind": "input",
          "name": "required",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "disabled",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "forceInvalid",
          "type": "boolean, BooleanInput",
          "required": false
        }
      ]
    }
  ],
  "collapsible": [
    {
      "className": "HlmCollapsible",
      "selector": "[hlmCollapsible],hlm-collapsible",
      "members": []
    },
    {
      "className": "HlmCollapsibleContent",
      "selector": "[hlmCollapsibleContent],hlm-collapsible-content",
      "members": []
    },
    {
      "className": "HlmCollapsibleTrigger",
      "selector": "button[hlmCollapsibleTrigger]",
      "members": []
    }
  ],
  "combobox": [
    {
      "className": "HlmCombobox",
      "selector": "[hlmCombobox],hlm-combobox",
      "members": []
    },
    {
      "className": "HlmComboboxChip",
      "selector": "hlm-combobox-chip",
      "members": [
        {
          "kind": "input",
          "name": "showRemove",
          "type": "boolean, BooleanInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmComboboxChipInput",
      "selector": "input[hlmComboboxChipInput]",
      "members": []
    },
    {
      "className": "HlmComboboxChipRemove",
      "selector": "button[hlmComboboxChipRemove]",
      "members": []
    },
    {
      "className": "HlmComboboxChips",
      "selector": "[hlmComboboxChips],hlm-combobox-chips",
      "members": [
        {
          "kind": "input",
          "name": "forceInvalid",
          "type": "boolean, BooleanInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmComboboxContent",
      "selector": "[hlmComboboxContent],hlm-combobox-content",
      "members": []
    },
    {
      "className": "HlmComboboxEmpty",
      "selector": "[hlmComboboxEmpty],hlm-combobox-empty",
      "members": []
    },
    {
      "className": "HlmComboboxGroup",
      "selector": "[hlmComboboxGroup]",
      "members": []
    },
    {
      "className": "HlmComboboxInput",
      "selector": "hlm-combobox-input",
      "members": [
        {
          "kind": "input",
          "name": "inputId",
          "type": "string",
          "required": false
        },
        {
          "kind": "input",
          "name": "placeholder",
          "type": "string",
          "required": false
        },
        {
          "kind": "input",
          "name": "showTrigger",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "showClear",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "forceInvalid",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "aria-invalid",
          "type": "boolean | undefined, BooleanInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmComboboxItem",
      "selector": "hlm-combobox-item",
      "members": []
    },
    {
      "className": "HlmComboboxLabel",
      "selector": "[hlmComboboxLabel]",
      "members": []
    },
    {
      "className": "HlmComboboxList",
      "selector": "[hlmComboboxList]",
      "members": []
    },
    {
      "className": "HlmComboboxMultiple",
      "selector": "[hlmComboboxMultiple],hlm-combobox-multiple",
      "members": []
    },
    {
      "className": "HlmComboboxPlaceholder",
      "selector": "[hlmComboboxPlaceholder],hlm-combobox-placeholder",
      "members": []
    },
    {
      "className": "HlmComboboxPortal",
      "selector": "[hlmComboboxPortal]",
      "members": []
    },
    {
      "className": "HlmComboboxSeparator",
      "selector": "[hlmComboboxSeparator]",
      "members": []
    },
    {
      "className": "HlmComboboxStatus",
      "selector": "[hlmComboboxStatus],hlm-combobox-status",
      "members": []
    },
    {
      "className": "HlmComboboxTrigger",
      "selector": "hlm-combobox-trigger",
      "members": [
        {
          "kind": "input",
          "name": "class",
          "type": "ClassValue",
          "required": false
        },
        {
          "kind": "input",
          "name": "buttonId",
          "type": "string",
          "required": false
        },
        {
          "kind": "input",
          "name": "variant",
          "type": "ButtonVariants['variant']",
          "required": false
        },
        {
          "kind": "input",
          "name": "forceInvalid",
          "type": "boolean, BooleanInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmComboboxValue",
      "selector": "[hlmComboboxValue],hlm-combobox-value",
      "members": []
    },
    {
      "className": "HlmComboboxValues",
      "selector": "[hlmComboboxValues]",
      "members": []
    },
    {
      "className": "HlmComboboxValueTemplate",
      "selector": "[hlmComboboxValueTemplate]",
      "members": []
    }
  ],
  "command": [
    {
      "className": "HlmCommand",
      "selector": "[hlmCommand],hlm-command",
      "members": []
    },
    {
      "className": "HlmCommandDialog",
      "selector": "hlm-command-dialog",
      "members": [
        {
          "kind": "input",
          "name": "title",
          "type": "string",
          "required": false
        },
        {
          "kind": "input",
          "name": "description",
          "type": "string",
          "required": false
        },
        {
          "kind": "input",
          "name": "state",
          "type": "BrnDialogState",
          "required": false
        },
        {
          "kind": "input",
          "name": "showCloseButton",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "dialogContentClass",
          "type": "ClassValue",
          "required": false
        },
        {
          "kind": "output",
          "name": "stateChange",
          "type": "BrnDialogState",
          "required": false
        }
      ]
    },
    {
      "className": "HlmCommandEmpty",
      "selector": "[hlmCommandEmpty]",
      "members": []
    },
    {
      "className": "HlmCommandEmptyState",
      "selector": "[hlmCommandEmptyState]",
      "members": []
    },
    {
      "className": "HlmCommandGroup",
      "selector": "[hlmCommandGroup],hlm-command-group",
      "members": []
    },
    {
      "className": "HlmCommandGroupLabel",
      "selector": "[hlmCommandGroupLabel],hlm-command-group-label",
      "members": []
    },
    {
      "className": "HlmCommandInput",
      "selector": "hlm-command-input",
      "members": [
        {
          "kind": "input",
          "name": "inputId",
          "type": "string | undefined",
          "required": false
        },
        {
          "kind": "input",
          "name": "placeholder",
          "type": "string",
          "required": false
        }
      ]
    },
    {
      "className": "HlmCommandItem",
      "selector": "button[hlmCommandItem],button[hlm-command-item]",
      "members": []
    },
    {
      "className": "HlmCommandList",
      "selector": "[hlmCommandList],hlm-command-list",
      "members": []
    },
    {
      "className": "HlmCommandSeparator",
      "selector": "[hlmCommandSeparator],hlm-command-separator",
      "members": []
    },
    {
      "className": "HlmCommandShortcut",
      "selector": "[hlmCommandShortcut],hlm-command-shortcut",
      "members": []
    }
  ],
  "context-menu": [
    {
      "className": "HlmContextMenuTrigger",
      "selector": "[hlmContextMenuTrigger]",
      "members": [
        {
          "kind": "input",
          "name": "disabled",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "align",
          "type": "MenuAlign",
          "required": false
        },
        {
          "kind": "input",
          "name": "side",
          "type": "MenuSide",
          "required": false
        }
      ]
    }
  ],
  "date-picker": [
    {
      "className": "HlmDatePicker",
      "selector": "hlm-date-picker",
      "members": [
        {
          "kind": "input",
          "name": "captionLayout",
          "type": "'dropdown' | 'label' | 'dropdown-months' | 'dropdown-years'",
          "required": false
        },
        {
          "kind": "input",
          "name": "min",
          "type": "T",
          "required": false
        },
        {
          "kind": "input",
          "name": "max",
          "type": "T",
          "required": false
        },
        {
          "kind": "input",
          "name": "disabled",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "date",
          "type": "T",
          "required": false
        },
        {
          "kind": "input",
          "name": "defaultFocusedDate",
          "type": "T",
          "required": false
        },
        {
          "kind": "input",
          "name": "autoCloseOnSelect",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "formatDate",
          "type": "unknown",
          "required": false
        },
        {
          "kind": "input",
          "name": "transformDate",
          "type": "unknown",
          "required": false
        },
        {
          "kind": "output",
          "name": "dateChange",
          "type": "T",
          "required": false
        }
      ]
    },
    {
      "className": "HlmDatePickerAnchor",
      "selector": "[hlmDatePickerAnchor]",
      "members": [
        {
          "kind": "input",
          "name": "hlmDatePickerAnchorFor",
          "type": "BrnPopover | undefined",
          "required": false
        }
      ]
    },
    {
      "className": "HlmDatePickerInput",
      "selector": "hlm-date-picker-input",
      "members": [
        {
          "kind": "input",
          "name": "inputValue",
          "type": "string",
          "required": false
        },
        {
          "kind": "input",
          "name": "parseDate",
          "type": "unknown",
          "required": false
        },
        {
          "kind": "input",
          "name": "forceInvalid",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "showClear",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "openOnClick",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "clearAriaLabel",
          "type": "string",
          "required": false
        },
        {
          "kind": "input",
          "name": "calendarAriaLabel",
          "type": "string",
          "required": false
        }
      ]
    },
    {
      "className": "HlmDatePickerMulti",
      "selector": "hlm-date-picker-multi",
      "members": [
        {
          "kind": "input",
          "name": "captionLayout",
          "type": "'dropdown' | 'label' | 'dropdown-months' | 'dropdown-years'",
          "required": false
        },
        {
          "kind": "input",
          "name": "min",
          "type": "T",
          "required": false
        },
        {
          "kind": "input",
          "name": "max",
          "type": "T",
          "required": false
        },
        {
          "kind": "input",
          "name": "minSelection",
          "type": "number, NumberInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "maxSelection",
          "type": "number, NumberInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "disabled",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "date",
          "type": "T[]",
          "required": false
        },
        {
          "kind": "input",
          "name": "autoCloseOnMaxSelection",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "formatDates",
          "type": "unknown",
          "required": false
        },
        {
          "kind": "input",
          "name": "transformDates",
          "type": "unknown",
          "required": false
        },
        {
          "kind": "output",
          "name": "dateChange",
          "type": "T[]",
          "required": false
        }
      ]
    },
    {
      "className": "HlmDatePickerTrigger",
      "selector": "hlm-date-picker-trigger",
      "members": [
        {
          "kind": "input",
          "name": "class",
          "type": "ClassValue",
          "required": false
        },
        {
          "kind": "input",
          "name": "buttonId",
          "type": "string",
          "required": false
        },
        {
          "kind": "input",
          "name": "forceInvalid",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "variant",
          "type": "ButtonVariants['variant']",
          "required": false
        },
        {
          "kind": "input",
          "name": "showTrigger",
          "type": "boolean, BooleanInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmDateRangePicker",
      "selector": "hlm-date-range-picker",
      "members": [
        {
          "kind": "input",
          "name": "captionLayout",
          "type": "'dropdown' | 'label' | 'dropdown-months' | 'dropdown-years'",
          "required": false
        },
        {
          "kind": "input",
          "name": "min",
          "type": "T",
          "required": false
        },
        {
          "kind": "input",
          "name": "max",
          "type": "T",
          "required": false
        },
        {
          "kind": "input",
          "name": "disabled",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "date",
          "type": "[T, T]",
          "required": false
        },
        {
          "kind": "input",
          "name": "autoCloseOnEndSelection",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "formatDates",
          "type": "unknown",
          "required": false
        },
        {
          "kind": "input",
          "name": "transformDates",
          "type": "unknown",
          "required": false
        },
        {
          "kind": "output",
          "name": "dateChange",
          "type": "[T, T] | null",
          "required": false
        }
      ]
    }
  ],
  "dialog": [
    {
      "className": "HlmDialog",
      "selector": "hlm-dialog",
      "members": []
    },
    {
      "className": "HlmDialogClose",
      "selector": "button[hlmDialogClose]",
      "members": []
    },
    {
      "className": "HlmDialogContent",
      "selector": "hlm-dialog-content",
      "members": [
        {
          "kind": "input",
          "name": "showCloseButton",
          "type": "boolean, BooleanInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmDialogDescription",
      "selector": "[hlmDialogDescription]",
      "members": []
    },
    {
      "className": "HlmDialogFooter",
      "selector": "[hlmDialogFooter],hlm-dialog-footer",
      "members": []
    },
    {
      "className": "HlmDialogHeader",
      "selector": "[hlmDialogHeader],hlm-dialog-header",
      "members": []
    },
    {
      "className": "HlmDialogOverlay",
      "selector": "[hlmDialogOverlay],hlm-dialog-overlay",
      "members": [
        {
          "kind": "input",
          "name": "class",
          "type": "ClassValue",
          "required": false
        }
      ]
    },
    {
      "className": "HlmDialogPortal",
      "selector": "[hlmDialogPortal]",
      "members": []
    },
    {
      "className": "HlmDialogTitle",
      "selector": "[hlmDialogTitle]",
      "members": []
    },
    {
      "className": "HlmDialogTrigger",
      "selector": "button[hlmDialogTrigger],button[hlmDialogTriggerFor]",
      "members": []
    }
  ],
  "drawer": [
    {
      "className": "HlmDrawer",
      "selector": "hlm-drawer",
      "members": []
    },
    {
      "className": "HlmDrawerClose",
      "selector": "button[hlmDrawerClose]",
      "members": []
    },
    {
      "className": "HlmDrawerContent",
      "selector": "hlm-drawer-content",
      "members": []
    },
    {
      "className": "HlmDrawerDescription",
      "selector": "[hlmDrawerDescription]",
      "members": []
    },
    {
      "className": "HlmDrawerFooter",
      "selector": "[hlmDrawerFooter],hlm-drawer-footer",
      "members": []
    },
    {
      "className": "HlmDrawerHeader",
      "selector": "[hlmDrawerHeader],hlm-drawer-header",
      "members": []
    },
    {
      "className": "HlmDrawerOverlay",
      "selector": "[hlmDrawerOverlay],hlm-drawer-overlay",
      "members": [
        {
          "kind": "input",
          "name": "class",
          "type": "ClassValue",
          "required": false
        }
      ]
    },
    {
      "className": "HlmDrawerPortal",
      "selector": "[hlmDrawerPortal]",
      "members": []
    },
    {
      "className": "HlmDrawerTitle",
      "selector": "[hlmDrawerTitle]",
      "members": []
    },
    {
      "className": "HlmDrawerTrigger",
      "selector": "button[hlmDrawerTrigger]",
      "members": []
    }
  ],
  "dropdown-menu": [
    {
      "className": "HlmDropdownMenu",
      "selector": "[hlmDropdownMenu],hlm-dropdown-menu",
      "members": [
        {
          "kind": "input",
          "name": "sideOffset",
          "type": "number, NumberInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmDropdownMenuCheckbox",
      "selector": "[hlmDropdownMenuCheckbox],[hlmDropdownMenuCheckboxItem]",
      "members": [
        {
          "kind": "input",
          "name": "inset",
          "type": "boolean, BooleanInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmDropdownMenuCheckboxCdk",
      "selector": "[hlmDropdownMenuCheckboxCdk]",
      "members": [
        {
          "kind": "input",
          "name": "keepOpen",
          "type": "boolean, BooleanInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmDropdownMenuCheckboxIndicator",
      "selector": "hlm-dropdown-menu-checkbox-indicator",
      "members": []
    },
    {
      "className": "HlmDropdownMenuFocusOnHover",
      "selector": "[hlmDropdownMenuFocusOnHover]",
      "members": []
    },
    {
      "className": "HlmDropdownMenuGroup",
      "selector": "[hlmDropdownMenuGroup],hlm-dropdown-menu-group",
      "members": []
    },
    {
      "className": "HlmDropdownMenuItem",
      "selector": "[hlmDropdownMenuItem],hlm-dropdown-menu-item",
      "members": [
        {
          "kind": "input",
          "name": "disabled",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "variant",
          "type": "'default' | 'destructive'",
          "required": false
        },
        {
          "kind": "input",
          "name": "inset",
          "type": "boolean, BooleanInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmDropdownMenuItemSubIndicator",
      "selector": "hlm-dropdown-menu-item-sub-indicator",
      "members": []
    },
    {
      "className": "HlmDropdownMenuLabel",
      "selector": "[hlmDropdownMenuLabel],hlm-dropdown-menu-label",
      "members": [
        {
          "kind": "input",
          "name": "inset",
          "type": "boolean, BooleanInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmDropdownMenuRadio",
      "selector": "[hlmDropdownMenuRadio]",
      "members": []
    },
    {
      "className": "HlmDropdownMenuRadioCdk",
      "selector": "[hlmDropdownMenuRadioCdk]",
      "members": [
        {
          "kind": "input",
          "name": "keepOpen",
          "type": "boolean, BooleanInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmDropdownMenuRadioIndicator",
      "selector": "hlm-dropdown-menu-radio-indicator",
      "members": []
    },
    {
      "className": "HlmDropdownMenuSeparator",
      "selector": "[hlmDropdownMenuSeparator],hlm-dropdown-menu-separator",
      "members": []
    },
    {
      "className": "HlmDropdownMenuShortcut",
      "selector": "[hlmDropdownMenuShortcut],hlm-dropdown-menu-shortcut",
      "members": []
    },
    {
      "className": "HlmDropdownMenuSub",
      "selector": "[hlmDropdownMenuSub],hlm-dropdown-menu-sub",
      "members": []
    },
    {
      "className": "HlmDropdownMenuSubTrigger",
      "selector": "[hlmDropdownMenuSubTrigger]",
      "members": [
        {
          "kind": "input",
          "name": "align",
          "type": "MenuAlign",
          "required": false
        },
        {
          "kind": "input",
          "name": "side",
          "type": "MenuSide",
          "required": false
        }
      ]
    },
    {
      "className": "HlmDropdownMenuTrigger",
      "selector": "[hlmDropdownMenuTrigger]",
      "members": [
        {
          "kind": "input",
          "name": "align",
          "type": "MenuAlign",
          "required": false
        },
        {
          "kind": "input",
          "name": "side",
          "type": "MenuSide",
          "required": false
        }
      ]
    }
  ],
  "empty": [
    {
      "className": "HlmEmpty",
      "selector": "[hlmEmpty],hlm-empty",
      "members": []
    },
    {
      "className": "HlmEmptyContent",
      "selector": "[hlmEmptyContent],hlm-empty-content",
      "members": []
    },
    {
      "className": "HlmEmptyDescription",
      "selector": "[hlmEmptyDescription]",
      "members": []
    },
    {
      "className": "HlmEmptyHeader",
      "selector": "[hlmEmptyHeader],hlm-empty-header",
      "members": []
    },
    {
      "className": "HlmEmptyMedia",
      "selector": "[hlmEmptyMedia],hlm-empty-media",
      "members": [
        {
          "kind": "input",
          "name": "variant",
          "type": "EmptyMediaVariants['variant']",
          "required": false
        }
      ]
    },
    {
      "className": "HlmEmptyTitle",
      "selector": "[hlmEmptyTitle]",
      "members": []
    }
  ],
  "field": [
    {
      "className": "HlmField",
      "selector": "[hlmField],hlm-field",
      "members": [
        {
          "kind": "input",
          "name": "orientation",
          "type": "FieldVariants['orientation']",
          "required": false
        }
      ]
    },
    {
      "className": "HlmFieldContent",
      "selector": "[hlmFieldContent],hlm-field-content",
      "members": []
    },
    {
      "className": "HlmFieldDescription",
      "selector": "[hlmFieldDescription],hlm-field-description",
      "members": [
        {
          "kind": "input",
          "name": "id",
          "type": "string",
          "required": false
        }
      ]
    },
    {
      "className": "HlmFieldError",
      "selector": "hlm-field-error",
      "members": [
        {
          "kind": "input",
          "name": "id",
          "type": "string",
          "required": false
        },
        {
          "kind": "input",
          "name": "validator",
          "type": "string",
          "required": false
        },
        {
          "kind": "input",
          "name": "forceShow",
          "type": "boolean, BooleanInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmFieldGroup",
      "selector": "[hlmFieldGroup],hlm-field-group",
      "members": []
    },
    {
      "className": "HlmFieldLabel",
      "selector": "[hlmFieldLabel],hlm-field-label",
      "members": []
    },
    {
      "className": "HlmFieldLegend",
      "selector": "legend[hlmFieldLegend]",
      "members": [
        {
          "kind": "input",
          "name": "variant",
          "type": "'label' | 'legend'",
          "required": false
        }
      ]
    },
    {
      "className": "HlmFieldSeparator",
      "selector": "hlm-field-separator",
      "members": []
    },
    {
      "className": "HlmFieldSet",
      "selector": "fieldset[hlmFieldSet]",
      "members": []
    },
    {
      "className": "HlmFieldTitle",
      "selector": "[hlmFieldTitle],hlm-field-title",
      "members": []
    }
  ],
  "hover-card": [
    {
      "className": "HlmHoverCard",
      "selector": "[hlmHoverCard],hlm-hover-card",
      "members": []
    },
    {
      "className": "HlmHoverCardContent",
      "selector": "[hlmHoverCardContent],hlm-hover-card-content",
      "members": []
    },
    {
      "className": "HlmHoverCardPortal",
      "selector": "[hlmHoverCardPortal],hlm-hover-card-portal",
      "members": []
    },
    {
      "className": "HlmHoverCardTrigger",
      "selector": "[hlmHoverCardTrigger]",
      "members": []
    }
  ],
  "input": [
    {
      "className": "HlmInput",
      "selector": "[hlmInput]",
      "members": []
    }
  ],
  "input-group": [
    {
      "className": "HlmInputGroup",
      "selector": "[hlmInputGroup],hlm-input-group",
      "members": []
    },
    {
      "className": "HlmInputGroupAddon",
      "selector": "[hlmInputGroupAddon],hlm-input-group-addon",
      "members": [
        {
          "kind": "input",
          "name": "align",
          "type": "InputGroupAddonVariants['align']",
          "required": false
        }
      ]
    },
    {
      "className": "HlmInputGroupButton",
      "selector": "button[hlmInputGroupButton]",
      "members": [
        {
          "kind": "input",
          "name": "size",
          "type": "InputGroupAddonVariants['size']",
          "required": false
        },
        {
          "kind": "input",
          "name": "type",
          "type": "'button' | 'submit' | 'reset'",
          "required": false
        }
      ]
    },
    {
      "className": "HlmInputGroupInput",
      "selector": "input[hlmInputGroupInput]",
      "members": []
    },
    {
      "className": "HlmInputGroupText",
      "selector": "[hlmInputGroupText],hlm-input-group-text",
      "members": []
    },
    {
      "className": "HlmInputGroupTextarea",
      "selector": "textarea[hlmInputGroupTextarea]",
      "members": []
    }
  ],
  "input-otp": [
    {
      "className": "HlmInputOtp",
      "selector": "brn-input-otp[hlmInputOtp], brn-input-otp[hlm]",
      "members": []
    },
    {
      "className": "HlmInputOtpFakeCaret",
      "selector": "hlm-input-otp-fake-caret",
      "members": []
    },
    {
      "className": "HlmInputOtpGroup",
      "selector": "[hlmInputOtpGroup],hlm-input-otp-group",
      "members": []
    },
    {
      "className": "HlmInputOtpSeparator",
      "selector": "hlm-input-otp-separator",
      "members": []
    },
    {
      "className": "HlmInputOtpSlot",
      "selector": "hlm-input-otp-slot",
      "members": [
        {
          "kind": "input",
          "name": "index",
          "type": "number, NumberInput",
          "required": true
        }
      ]
    }
  ],
  "item": [
    {
      "className": "HlmItem",
      "selector": "[hlmItem],hlm-item",
      "members": [
        {
          "kind": "input",
          "name": "variant",
          "type": "ItemVariants['variant']",
          "required": false
        },
        {
          "kind": "input",
          "name": "size",
          "type": "ItemVariants['size']",
          "required": false
        }
      ]
    },
    {
      "className": "HlmItemActions",
      "selector": "[hlmItemActions],hlm-item-actions",
      "members": []
    },
    {
      "className": "HlmItemContent",
      "selector": "[hlmItemContent],hlm-item-content",
      "members": []
    },
    {
      "className": "HlmItemDescription",
      "selector": "[hlmItemDescription],hlm-item-description",
      "members": []
    },
    {
      "className": "HlmItemFooter",
      "selector": "[hlmItemFooter],hlm-item-footer",
      "members": []
    },
    {
      "className": "HlmItemGroup",
      "selector": "[hlmItemGroup],hlm-item-group",
      "members": []
    },
    {
      "className": "HlmItemHeader",
      "selector": "[hlmItemHeader],hlm-item-header",
      "members": []
    },
    {
      "className": "HlmItemMedia",
      "selector": "[hlmItemMedia],hlm-item-media",
      "members": [
        {
          "kind": "input",
          "name": "variant",
          "type": "ItemMediaVariants['variant']",
          "required": false
        }
      ]
    },
    {
      "className": "HlmItemSeparator",
      "selector": "[hlmItemSeparator],hlm-item-separator",
      "members": []
    },
    {
      "className": "HlmItemTitle",
      "selector": "[hlmItemTitle],hlm-item-title",
      "members": []
    }
  ],
  "kbd": [
    {
      "className": "HlmKbd",
      "selector": "kbd[hlmKbd]",
      "members": []
    },
    {
      "className": "HlmKbdGroup",
      "selector": "kbd[hlmKbdGroup]",
      "members": []
    }
  ],
  "label": [
    {
      "className": "HlmLabel",
      "selector": "[hlmLabel]",
      "members": []
    }
  ],
  "menubar": [
    {
      "className": "HlmMenubar",
      "selector": "[hlmMenubar],hlm-menubar",
      "members": []
    },
    {
      "className": "HlmMenubarTrigger",
      "selector": "button[hlmMenubarTrigger]",
      "members": [
        {
          "kind": "input",
          "name": "disabled",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "align",
          "type": "MenuAlign",
          "required": false
        },
        {
          "kind": "input",
          "name": "side",
          "type": "MenuSide",
          "required": false
        }
      ]
    }
  ],
  "native-select": [
    {
      "className": "HlmNativeSelect",
      "selector": "hlm-native-select",
      "members": [
        {
          "kind": "input",
          "name": "selectId",
          "type": "string",
          "required": false
        },
        {
          "kind": "input",
          "name": "selectClass",
          "type": "ClassValue",
          "required": false
        },
        {
          "kind": "input",
          "name": "selectIconClass",
          "type": "ClassValue",
          "required": false
        },
        {
          "kind": "input",
          "name": "size",
          "type": "'sm' | 'default'",
          "required": false
        },
        {
          "kind": "input",
          "name": "disabled",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "forceInvalid",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "aria-invalid",
          "type": "boolean | undefined, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "value",
          "type": "string | undefined | null",
          "required": false
        },
        {
          "kind": "output",
          "name": "valueChange",
          "type": "string | undefined | null",
          "required": false
        }
      ]
    },
    {
      "className": "HlmNativeSelectOptGroup",
      "selector": "optgroup[hlmNativeSelectOptGroup]",
      "members": []
    },
    {
      "className": "HlmNativeSelectOption",
      "selector": "option[hlmNativeSelectOption]",
      "members": []
    }
  ],
  "navigation-menu": [
    {
      "className": "HlmNavigationMenu",
      "selector": "nav[hlmNavigationMenu]",
      "members": []
    },
    {
      "className": "HlmNavigationMenuContent",
      "selector": "[hlmNavigationMenuContent],hlm-navigation-menu-content",
      "members": [
        {
          "kind": "input",
          "name": "navOffset",
          "type": "number, NumberInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmNavigationMenuItem",
      "selector": "li[hlmNavigationMenuItem]",
      "members": []
    },
    {
      "className": "HlmNavigationMenuLink",
      "selector": "a[hlmNavigationMenuLink]",
      "members": []
    },
    {
      "className": "HlmNavigationMenuList",
      "selector": "ul[hlmNavigationMenuList]",
      "members": []
    },
    {
      "className": "HlmNavigationMenuPortal",
      "selector": "[hlmNavigationMenuPortal]",
      "members": []
    },
    {
      "className": "HlmNavigationMenuTrigger",
      "selector": "button[hlmNavigationMenuTrigger]",
      "members": []
    }
  ],
  "pagination": [
    {
      "className": "HlmNumberedPagination",
      "selector": "hlm-numbered-pagination",
      "members": [
        {
          "kind": "model",
          "name": "currentPage",
          "type": "number",
          "required": true
        },
        {
          "kind": "model",
          "name": "itemsPerPage",
          "type": "number",
          "required": true
        },
        {
          "kind": "input",
          "name": "totalItems",
          "type": "number, NumberInput",
          "required": true
        },
        {
          "kind": "input",
          "name": "maxSize",
          "type": "number, NumberInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "showEdges",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "pageSizes",
          "type": "number[]",
          "required": false
        }
      ]
    },
    {
      "className": "HlmNumberedPaginationQueryParams",
      "selector": "hlm-numbered-pagination-query-params",
      "members": [
        {
          "kind": "model",
          "name": "currentPage",
          "type": "number",
          "required": true
        },
        {
          "kind": "model",
          "name": "itemsPerPage",
          "type": "number",
          "required": true
        },
        {
          "kind": "input",
          "name": "totalItems",
          "type": "number, NumberInput",
          "required": true
        },
        {
          "kind": "input",
          "name": "link",
          "type": "string",
          "required": false
        },
        {
          "kind": "input",
          "name": "maxSize",
          "type": "number, NumberInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "showEdges",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "pageSizes",
          "type": "number[]",
          "required": false
        }
      ]
    },
    {
      "className": "HlmPagination",
      "selector": "[hlmPagination],hlm-pagination",
      "members": [
        {
          "kind": "input",
          "name": "aria-label",
          "type": "string",
          "required": false
        }
      ]
    },
    {
      "className": "HlmPaginationContent",
      "selector": "ul[hlmPaginationContent]",
      "members": []
    },
    {
      "className": "HlmPaginationEllipsis",
      "selector": "hlm-pagination-ellipsis",
      "members": [
        {
          "kind": "input",
          "name": "srOnlyText",
          "type": "string",
          "required": false
        }
      ]
    },
    {
      "className": "HlmPaginationItem",
      "selector": "li[hlmPaginationItem]",
      "members": []
    },
    {
      "className": "HlmPaginationLink",
      "selector": "[hlmPaginationLink]",
      "members": [
        {
          "kind": "input",
          "name": "isActive",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "size",
          "type": "ButtonVariants['size']",
          "required": false
        },
        {
          "kind": "input",
          "name": "link",
          "type": "RouterLink['routerLink']",
          "required": false
        }
      ]
    },
    {
      "className": "HlmPaginationNext",
      "selector": "hlm-pagination-next",
      "members": [
        {
          "kind": "input",
          "name": "class",
          "type": "ClassValue",
          "required": false
        },
        {
          "kind": "input",
          "name": "link",
          "type": "RouterLink['routerLink']",
          "required": false
        },
        {
          "kind": "input",
          "name": "queryParams",
          "type": "RouterLink['queryParams']",
          "required": false
        },
        {
          "kind": "input",
          "name": "queryParamsHandling",
          "type": "RouterLink['queryParamsHandling']",
          "required": false
        },
        {
          "kind": "input",
          "name": "aria-label",
          "type": "string",
          "required": false
        },
        {
          "kind": "input",
          "name": "text",
          "type": "string",
          "required": false
        },
        {
          "kind": "input",
          "name": "iconOnly",
          "type": "boolean, BooleanInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmPaginationPrevious",
      "selector": "hlm-pagination-previous",
      "members": [
        {
          "kind": "input",
          "name": "class",
          "type": "ClassValue",
          "required": false
        },
        {
          "kind": "input",
          "name": "link",
          "type": "RouterLink['routerLink']",
          "required": false
        },
        {
          "kind": "input",
          "name": "queryParams",
          "type": "RouterLink['queryParams']",
          "required": false
        },
        {
          "kind": "input",
          "name": "queryParamsHandling",
          "type": "RouterLink['queryParamsHandling']",
          "required": false
        },
        {
          "kind": "input",
          "name": "aria-label",
          "type": "string",
          "required": false
        },
        {
          "kind": "input",
          "name": "text",
          "type": "string",
          "required": false
        },
        {
          "kind": "input",
          "name": "iconOnly",
          "type": "boolean, BooleanInput",
          "required": false
        }
      ]
    }
  ],
  "popover": [
    {
      "className": "HlmPopover",
      "selector": "[hlmPopover],hlm-popover",
      "members": []
    },
    {
      "className": "HlmPopoverContent",
      "selector": "[hlmPopoverContent],hlm-popover-content",
      "members": []
    },
    {
      "className": "HlmPopoverDescription",
      "selector": "[hlmPopoverDescription]",
      "members": []
    },
    {
      "className": "HlmPopoverHeader",
      "selector": "[hlmPopoverHeader],hlm-popover-header",
      "members": []
    },
    {
      "className": "HlmPopoverPortal",
      "selector": "[hlmPopoverPortal]",
      "members": []
    },
    {
      "className": "HlmPopoverTitle",
      "selector": "[hlmPopoverTitle]",
      "members": []
    },
    {
      "className": "HlmPopoverTrigger",
      "selector": "button[hlmPopoverTrigger],button[hlmPopoverTriggerFor]",
      "members": []
    }
  ],
  "progress": [
    {
      "className": "HlmProgress",
      "selector": "hlm-progress,[hlmProgress]",
      "members": []
    },
    {
      "className": "HlmProgressIndicator",
      "selector": "[hlmProgressIndicator],hlm-progress-indicator",
      "members": []
    }
  ],
  "radio-group": [
    {
      "className": "HlmRadio",
      "selector": "hlm-radio",
      "members": [
        {
          "kind": "input",
          "name": "class",
          "type": "ClassValue",
          "required": false
        },
        {
          "kind": "input",
          "name": "inputId",
          "type": "string | undefined",
          "required": false
        },
        {
          "kind": "input",
          "name": "aria-label",
          "type": "string | undefined",
          "required": false
        },
        {
          "kind": "input",
          "name": "aria-labelledby",
          "type": "string | undefined",
          "required": false
        },
        {
          "kind": "input",
          "name": "aria-describedby",
          "type": "string | undefined",
          "required": false
        },
        {
          "kind": "input",
          "name": "value",
          "type": "T",
          "required": true
        },
        {
          "kind": "input",
          "name": "required",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "disabled",
          "type": "boolean, BooleanInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmRadioGroup",
      "selector": "[hlmRadioGroup],hlm-radio-group",
      "members": [
        {
          "kind": "input",
          "name": "class",
          "type": "ClassValue",
          "required": false
        }
      ]
    },
    {
      "className": "HlmRadioIndicator",
      "selector": "hlm-radio-indicator",
      "members": []
    }
  ],
  "resizable": [
    {
      "className": "HlmResizableGroup",
      "selector": "[hlmResizableGroup],hlm-resizable-group",
      "members": []
    },
    {
      "className": "HlmResizableHandle",
      "selector": "hlm-resizable-handle",
      "members": []
    },
    {
      "className": "HlmResizablePanel",
      "selector": "[hlmResizablePanel],hlm-resizable-panel",
      "members": []
    }
  ],
  "scroll-area": [
    {
      "className": "HlmScrollArea",
      "selector": "ng-scrollbar[hlm],ng-scrollbar[hlmScrollbar]",
      "members": []
    }
  ],
  "select": [
    {
      "className": "HlmSelect",
      "selector": "[hlmSelect],hlm-select",
      "members": []
    },
    {
      "className": "HlmSelectContent",
      "selector": "hlm-select-content",
      "members": [
        {
          "kind": "input",
          "name": "showScroll",
          "type": "boolean, BooleanInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmSelectGroup",
      "selector": "[hlmSelectGroup],hlm-select-group",
      "members": []
    },
    {
      "className": "HlmSelectItem",
      "selector": "hlm-select-item",
      "members": []
    },
    {
      "className": "HlmSelectLabel",
      "selector": "[hlmSelectLabel],hlm-select-label",
      "members": []
    },
    {
      "className": "HlmSelectMultiple",
      "selector": "[hlmSelectMultiple],hlm-select-multiple",
      "members": []
    },
    {
      "className": "HlmSelectPlaceholder",
      "selector": "[hlmSelectPlaceholder],hlm-select-placeholder",
      "members": []
    },
    {
      "className": "HlmSelectPortal",
      "selector": "[hlmSelectPortal]",
      "members": []
    },
    {
      "className": "HlmSelectScrollDown",
      "selector": "hlm-select-scroll-down",
      "members": []
    },
    {
      "className": "HlmSelectScrollUp",
      "selector": "hlm-select-scroll-up",
      "members": []
    },
    {
      "className": "HlmSelectSeparator",
      "selector": "[hlmSelectSeparator],hlm-select-separator",
      "members": []
    },
    {
      "className": "HlmSelectTrigger",
      "selector": "hlm-select-trigger",
      "members": [
        {
          "kind": "input",
          "name": "class",
          "type": "ClassValue",
          "required": false
        },
        {
          "kind": "input",
          "name": "buttonId",
          "type": "string",
          "required": false
        },
        {
          "kind": "input",
          "name": "size",
          "type": "'default' | 'sm'",
          "required": false
        },
        {
          "kind": "input",
          "name": "forceInvalid",
          "type": "boolean, BooleanInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmSelectValue",
      "selector": "[hlmSelectValue],hlm-select-value",
      "members": []
    },
    {
      "className": "HlmSelectValues",
      "selector": "[hlmSelectValues]",
      "members": []
    },
    {
      "className": "HlmSelectValuesContent",
      "selector": "[hlmSelectValuesContent],hlm-select-values-content",
      "members": []
    },
    {
      "className": "HlmSelectValueTemplate",
      "selector": "[hlmSelectValueTemplate]",
      "members": []
    }
  ],
  "separator": [
    {
      "className": "HlmSeparator",
      "selector": "[hlmSeparator],hlm-separator",
      "members": []
    }
  ],
  "sheet": [
    {
      "className": "HlmSheet",
      "selector": "hlm-sheet",
      "members": []
    },
    {
      "className": "HlmSheetClose",
      "selector": "button[hlmSheetClose]",
      "members": []
    },
    {
      "className": "HlmSheetContent",
      "selector": "hlm-sheet-content",
      "members": [
        {
          "kind": "input",
          "name": "showCloseButton",
          "type": "boolean, BooleanInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmSheetDescription",
      "selector": "[hlmSheetDescription]",
      "members": []
    },
    {
      "className": "HlmSheetFooter",
      "selector": "[hlmSheetFooter],hlm-sheet-footer",
      "members": []
    },
    {
      "className": "HlmSheetHeader",
      "selector": "[hlmSheetHeader],hlm-sheet-header",
      "members": []
    },
    {
      "className": "HlmSheetOverlay",
      "selector": "[hlmSheetOverlay],hlm-sheet-overlay",
      "members": [
        {
          "kind": "input",
          "name": "class",
          "type": "ClassValue",
          "required": false
        }
      ]
    },
    {
      "className": "HlmSheetPortal",
      "selector": "[hlmSheetPortal]",
      "members": []
    },
    {
      "className": "HlmSheetTitle",
      "selector": "[hlmSheetTitle]",
      "members": []
    },
    {
      "className": "HlmSheetTrigger",
      "selector": "button[hlmSheetTrigger]",
      "members": []
    }
  ],
  "sidebar": [
    {
      "className": "HlmSidebar",
      "selector": "hlm-sidebar",
      "members": [
        {
          "kind": "input",
          "name": "sidebarWidthMobile",
          "type": "string",
          "required": false
        },
        {
          "kind": "input",
          "name": "side",
          "type": "'left' | 'right'",
          "required": false
        },
        {
          "kind": "input",
          "name": "variant",
          "type": "SidebarVariant",
          "required": false
        },
        {
          "kind": "input",
          "name": "collapsible",
          "type": "'offcanvas' | 'icon' | 'none'",
          "required": false
        },
        {
          "kind": "input",
          "name": "sidebarContainerClass",
          "type": "ClassValue",
          "required": false
        }
      ]
    },
    {
      "className": "HlmSidebarContent",
      "selector": "[hlmSidebarContent],hlm-sidebar-content",
      "members": []
    },
    {
      "className": "HlmSidebarFooter",
      "selector": "[hlmSidebarFooter],hlm-sidebar-footer",
      "members": []
    },
    {
      "className": "HlmSidebarGroup",
      "selector": "[hlmSidebarGroup],hlm-sidebar-group",
      "members": []
    },
    {
      "className": "HlmSidebarGroupAction",
      "selector": "button[hlmSidebarGroupAction]",
      "members": []
    },
    {
      "className": "HlmSidebarGroupContent",
      "selector": "div[hlmSidebarGroupContent]",
      "members": []
    },
    {
      "className": "HlmSidebarGroupLabel",
      "selector": "div[hlmSidebarGroupLabel], button[hlmSidebarGroupLabel]",
      "members": []
    },
    {
      "className": "HlmSidebarHeader",
      "selector": "[hlmSidebarHeader],hlm-sidebar-header",
      "members": []
    },
    {
      "className": "HlmSidebarInput",
      "selector": "input[hlmSidebarInput]",
      "members": []
    },
    {
      "className": "HlmSidebarInset",
      "selector": "main[hlmSidebarInset]",
      "members": []
    },
    {
      "className": "HlmSidebarMenu",
      "selector": "ul[hlmSidebarMenu]",
      "members": []
    },
    {
      "className": "HlmSidebarMenuAction",
      "selector": "button[hlmSidebarMenuAction]",
      "members": [
        {
          "kind": "input",
          "name": "showOnHover",
          "type": "boolean, BooleanInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmSidebarMenuBadge",
      "selector": "[hlmSidebarMenuBadge],hlm-sidebar-menu-badge",
      "members": []
    },
    {
      "className": "HlmSidebarMenuButton",
      "selector": "button[hlmSidebarMenuButton], a[hlmSidebarMenuButton]",
      "members": [
        {
          "kind": "input",
          "name": "variant",
          "type": "'default' | 'outline'",
          "required": false
        },
        {
          "kind": "input",
          "name": "size",
          "type": "'default' | 'sm' | 'lg'",
          "required": false
        },
        {
          "kind": "input",
          "name": "isActive",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "closeMobileSidebarOnClick",
          "type": "boolean, BooleanInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmSidebarMenuItem",
      "selector": "li[hlmSidebarMenuItem]",
      "members": []
    },
    {
      "className": "HlmSidebarMenuSkeleton",
      "selector": "hlm-sidebar-menu-skeleton,div[hlmSidebarMenuSkeleton]",
      "members": [
        {
          "kind": "input",
          "name": "showIcon",
          "type": "boolean, BooleanInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmSidebarMenuSub",
      "selector": "ul[hlmSidebarMenuSub]",
      "members": []
    },
    {
      "className": "HlmSidebarMenuSubButton",
      "selector": "a[hlmSidebarMenuSubButton], button[hlmSidebarMenuSubButton]",
      "members": [
        {
          "kind": "input",
          "name": "closeMobileSidebarOnClick",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "size",
          "type": "'sm' | 'md'",
          "required": false
        },
        {
          "kind": "input",
          "name": "isActive",
          "type": "boolean, BooleanInput",
          "required": false
        }
      ]
    },
    {
      "className": "HlmSidebarMenuSubItem",
      "selector": "li[hlmSidebarMenuSubItem]",
      "members": []
    },
    {
      "className": "HlmSidebarRail",
      "selector": "button[hlmSidebarRail]",
      "members": [
        {
          "kind": "input",
          "name": "aria-label",
          "type": "string",
          "required": false
        }
      ]
    },
    {
      "className": "HlmSidebarSeparator",
      "selector": "[hlmSidebarSeparator],hlm-sidebar-separator",
      "members": []
    },
    {
      "className": "HlmSidebarTrigger",
      "selector": "button[hlmSidebarTrigger]",
      "members": []
    },
    {
      "className": "HlmSidebarWrapper",
      "selector": "[hlmSidebarWrapper],hlm-sidebar-wrapper",
      "members": [
        {
          "kind": "input",
          "name": "sidebarWidth",
          "type": "string",
          "required": false
        },
        {
          "kind": "input",
          "name": "sidebarWidthIcon",
          "type": "string",
          "required": false
        }
      ]
    }
  ],
  "skeleton": [
    {
      "className": "HlmSkeleton",
      "selector": "[hlmSkeleton],hlm-skeleton",
      "members": []
    }
  ],
  "slider": [
    {
      "className": "HlmSlider",
      "selector": "hlm-slider, brn-slider [hlm]",
      "members": []
    }
  ],
  "sonner": [
    {
      "className": "HlmToaster",
      "selector": "hlm-toaster",
      "members": [
        {
          "kind": "input",
          "name": "invert",
          "type": "ToasterProps['invert'], BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "theme",
          "type": "ToasterProps['theme']",
          "required": false
        },
        {
          "kind": "input",
          "name": "position",
          "type": "ToasterProps['position']",
          "required": false
        },
        {
          "kind": "input",
          "name": "hotKey",
          "type": "ToasterProps['hotkey']",
          "required": false
        },
        {
          "kind": "input",
          "name": "richColors",
          "type": "ToasterProps['richColors'], BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "expand",
          "type": "ToasterProps['expand'], BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "duration",
          "type": "ToasterProps['duration'], NumberInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "visibleToasts",
          "type": "ToasterProps['visibleToasts'], NumberInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "closeButton",
          "type": "ToasterProps['closeButton'], BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "toastOptions",
          "type": "ToasterProps['toastOptions']",
          "required": false
        },
        {
          "kind": "input",
          "name": "offset",
          "type": "ToasterProps['offset']",
          "required": false
        },
        {
          "kind": "input",
          "name": "class",
          "type": "ClassValue",
          "required": false
        }
      ]
    }
  ],
  "spinner": [
    {
      "className": "HlmSpinner",
      "selector": "hlm-spinner",
      "members": [
        {
          "kind": "input",
          "name": "icon",
          "type": "string",
          "required": false
        },
        {
          "kind": "input",
          "name": "aria-label",
          "type": "string",
          "required": false
        }
      ]
    }
  ],
  "switch": [
    {
      "className": "HlmSwitch",
      "selector": "hlm-switch",
      "members": [
        {
          "kind": "input",
          "name": "class",
          "type": "ClassValue",
          "required": false
        },
        {
          "kind": "input",
          "name": "checked",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "output",
          "name": "checkedChange",
          "type": "boolean",
          "required": false
        },
        {
          "kind": "input",
          "name": "disabled",
          "type": "boolean, BooleanInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "size",
          "type": "BrnSwitchSize",
          "required": false
        },
        {
          "kind": "input",
          "name": "inputId",
          "type": "string | null",
          "required": false
        },
        {
          "kind": "input",
          "name": "aria-label",
          "type": "string | null",
          "required": false
        },
        {
          "kind": "input",
          "name": "aria-labelledby",
          "type": "string | null",
          "required": false
        },
        {
          "kind": "input",
          "name": "aria-describedby",
          "type": "string | null",
          "required": false
        }
      ]
    },
    {
      "className": "HlmSwitchThumb",
      "selector": "brn-switch-thumb[hlm],[hlmSwitchThumb]",
      "members": []
    }
  ],
  "table": [
    {
      "className": "HlmCaption",
      "selector": "caption[hlmCaption],caption[hlmTableCaption]",
      "members": []
    },
    {
      "className": "HlmTable",
      "selector": "table[hlmTable]",
      "members": []
    },
    {
      "className": "HlmTableContainer",
      "selector": "div[hlmTableContainer]",
      "members": []
    },
    {
      "className": "HlmTBody",
      "selector": "tbody[hlmTBody],tbody[hlmTableBody]",
      "members": []
    },
    {
      "className": "HlmTd",
      "selector": "td[hlmTd],td[hlmTableCell]",
      "members": []
    },
    {
      "className": "HlmTFoot",
      "selector": "tfoot[hlmTFoot],tfoot[hlmTableFooter]",
      "members": []
    },
    {
      "className": "HlmTh",
      "selector": "th[hlmTh],th[hlmTableHead]",
      "members": []
    },
    {
      "className": "HlmTHead",
      "selector": "thead[hlmTHead],thead[hlmTableHeader]",
      "members": []
    },
    {
      "className": "HlmTr",
      "selector": "tr[hlmTr],tr[hlmTableRow]",
      "members": []
    }
  ],
  "tabs": [
    {
      "className": "HlmTabs",
      "selector": "[hlmTabs],hlm-tabs",
      "members": [
        {
          "kind": "input",
          "name": "tab",
          "type": "string",
          "required": true
        }
      ]
    },
    {
      "className": "HlmTabsContent",
      "selector": "[hlmTabsContent]",
      "members": [
        {
          "kind": "input",
          "name": "hlmTabsContent",
          "type": "string",
          "required": true
        }
      ]
    },
    {
      "className": "HlmTabsContentLazy",
      "selector": "ng-template[hlmTabsContentLazy]",
      "members": []
    },
    {
      "className": "HlmTabsList",
      "selector": "[hlmTabsList],hlm-tabs-list",
      "members": [
        {
          "kind": "input",
          "name": "variant",
          "type": "ListVariants['variant']",
          "required": false
        }
      ]
    },
    {
      "className": "HlmTabsPaginatedList",
      "selector": "hlm-paginated-tabs-list",
      "members": [
        {
          "kind": "input",
          "name": "tabListClass",
          "type": "ClassValue",
          "required": false
        },
        {
          "kind": "input",
          "name": "paginationButtonClass",
          "type": "ClassValue",
          "required": false
        }
      ]
    },
    {
      "className": "HlmTabsTrigger",
      "selector": "[hlmTabsTrigger]",
      "members": [
        {
          "kind": "input",
          "name": "hlmTabsTrigger",
          "type": "string",
          "required": true
        }
      ]
    }
  ],
  "textarea": [
    {
      "className": "HlmTextarea",
      "selector": "[hlmTextarea]",
      "members": []
    }
  ],
  "toggle": [
    {
      "className": "HlmToggle",
      "selector": "button[hlmToggle]",
      "members": [
        {
          "kind": "input",
          "name": "variant",
          "type": "ToggleVariants['variant']",
          "required": false
        },
        {
          "kind": "input",
          "name": "size",
          "type": "ToggleVariants['size']",
          "required": false
        }
      ]
    }
  ],
  "toggle-group": [
    {
      "className": "HlmToggleGroup",
      "selector": "[hlmToggleGroup],hlm-toggle-group",
      "members": [
        {
          "kind": "input",
          "name": "variant",
          "type": "ToggleVariants['variant']",
          "required": false
        },
        {
          "kind": "input",
          "name": "size",
          "type": "ToggleVariants['size']",
          "required": false
        },
        {
          "kind": "input",
          "name": "spacing",
          "type": "number, NumberInput",
          "required": false
        },
        {
          "kind": "input",
          "name": "orientation",
          "type": "'horizontal' | 'vertical'",
          "required": false
        }
      ]
    },
    {
      "className": "HlmToggleGroupItem",
      "selector": "button[hlmToggleGroupItem]",
      "members": [
        {
          "kind": "input",
          "name": "variant",
          "type": "ToggleVariants['variant']",
          "required": false
        },
        {
          "kind": "input",
          "name": "size",
          "type": "ToggleVariants['size']",
          "required": false
        }
      ]
    }
  ],
  "tooltip": [
    {
      "className": "HlmTooltip",
      "selector": "[hlmTooltip]",
      "members": []
    }
  ],
  "typography": [
    {
      "className": "HlmBlockquote",
      "selector": "[hlmBlockquote]",
      "members": []
    },
    {
      "className": "HlmCode",
      "selector": "[hlmCode]",
      "members": []
    },
    {
      "className": "HlmH1",
      "selector": "[hlmH1]",
      "members": []
    },
    {
      "className": "HlmH2",
      "selector": "[hlmH2]",
      "members": []
    },
    {
      "className": "HlmH3",
      "selector": "[hlmH3]",
      "members": []
    },
    {
      "className": "HlmH4",
      "selector": "[hlmH4]",
      "members": []
    },
    {
      "className": "HlmLarge",
      "selector": "[hlmLarge]",
      "members": []
    },
    {
      "className": "HlmLead",
      "selector": "[hlmLead]",
      "members": []
    },
    {
      "className": "HlmMuted",
      "selector": "[hlmMuted]",
      "members": []
    },
    {
      "className": "HlmP",
      "selector": "[hlmP]",
      "members": []
    },
    {
      "className": "HlmSmall",
      "selector": "[hlmSmall]",
      "members": []
    },
    {
      "className": "HlmUl",
      "selector": "[hlmUl]",
      "members": []
    }
  ]
} as const;
