/**
 * Generates the showcase's API tables from the vendored helm sources.
 *
 * The alternative — hand-writing 56 API tables — restates facts the component
 * files already carry, so they would drift the first time spartan is upgraded.
 * This reads libs/ui and emits a typed map the showcase imports.
 *
 * Run via `npm run showcase:api`; `npm run verify` checks the result is fresh.
 */
import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';

const UI_ROOT = join('frontend', 'libs', 'ui');
const OUT = join('frontend', 'src', 'app', 'showcase', 'component-api.generated.ts');

export interface ApiMember {
  readonly kind: 'input' | 'output' | 'model';
  readonly name: string;
  readonly type: string;
  readonly required: boolean;
}

export interface ApiClass {
  readonly className: string;
  readonly selector: string;
  readonly members: readonly ApiMember[];
}

const walk = (dir: string): string[] =>
  readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
    e.isDirectory() ? walk(join(dir, e.name)) : [join(dir, e.name)],
  );

/** `public readonly foo = input<T>(...)` / `input.required<T>()` / `output<T>()` / `model<T>()` */
const MEMBER = /readonly\s+(\w+)\s*=\s*(input|output|model)(\.required)?\s*<\s*([^>]*?)\s*>?\s*\(/g;
/** the alias wins when present: it is what a consumer actually binds */
const ALIAS = /alias:\s*'([^']+)'/;

function parseFile(src: string): ApiClass[] {
  const out: ApiClass[] = [];
  // Split on decorators so each chunk holds one class and its metadata.
  const chunks = src.split(/@(?=Component\(|Directive\()/).slice(1);

  for (const chunk of chunks) {
    const selector = chunk.match(/selector:\s*'([^']+)'/)?.[1];
    const className = chunk.match(/export class (\w+)/)?.[1];
    if (!selector || !className) continue;

    const members: ApiMember[] = [];
    for (const m of chunk.matchAll(MEMBER)) {
      const [, prop, kind, required, type] = m;
      // The alias must come from THIS member's own options object. Scanning a
      // fixed window past the match instead reads the *next* member's alias —
      // which duplicated aria-label across every ARIA input on first run.
      const from = m.index! + m[0].length;
      const nextMember = chunk.slice(from).search(/\breadonly\s+\w+\s*=\s*(input|output|model)\b/);
      const tail = chunk.slice(from, from + (nextMember === -1 ? 400 : nextMember));
      const aliased = tail.match(ALIAS)?.[1];
      members.push({
        kind: kind as ApiMember['kind'],
        name: aliased ?? prop,
        type: (type || 'unknown').replace(/\s+/g, ' ').trim(),
        required: Boolean(required),
      });
    }
    out.push({ className, selector, members });
  }
  return out;
}

export function buildApi(uiRoot = UI_ROOT): Record<string, ApiClass[]> {
  const api: Record<string, ApiClass[]> = {};
  for (const slug of readdirSync(uiRoot).sort()) {
    const lib = join(uiRoot, slug, 'src', 'lib');
    if (!existsSync(lib)) continue;
    const classes = walk(lib)
      .filter((f) => f.endsWith('.ts'))
      .flatMap((f) => parseFile(readFileSync(f, 'utf8')));
    if (classes.length) api[slug] = classes.sort((a, b) => a.className.localeCompare(b.className));
  }
  return api;
}

export function render(api: Record<string, ApiClass[]>): string {
  return `// GENERATED by tools/showcase-api — do not edit. Run \`npm run showcase:api\`.
import type { ApiClass } from './component-api.types';

export const COMPONENT_API: Readonly<Record<string, readonly ApiClass[]>> = ${JSON.stringify(api, null, 2)} as const;
`;
}

// endsWith, not includes: `includes('showcase-api')` also matches
// showcase-api.test.ts and would run the generator during the test suite.
if (process.argv[1]?.endsWith('showcase-api.ts')) {
  const api = buildApi();
  const rendered = render(api);
  const classes = Object.values(api).reduce((n, cs) => n + cs.length, 0);

  // --check is what makes the "verify enforces this" claim true. Without it the
  // generated file silently goes stale the first time a component is added.
  if (process.argv.includes('--check')) {
    const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
    if (current !== rendered) {
      console.error('Showcase API is stale. Run `npm run showcase:api` and commit.');
      process.exit(1);
    }
    console.log(`Showcase API fresh (${Object.keys(api).length} components, ${classes} classes).`);
  } else {
    mkdirSync(dirname(OUT), { recursive: true });
    writeFileSync(OUT, rendered, 'utf8');
    console.log(`Wrote showcase API: ${Object.keys(api).length} components, ${classes} classes → ${OUT}`);
  }
}
