import { test } from 'node:test';
import assert from 'node:assert/strict';
import { buildApi, render } from './showcase-api.ts';

// The parser is two regexes over generated TypeScript, and its first run shipped
// a real defect: the alias lookahead ran past its own statement and duplicated
// aria-label across every ARIA input. These tests exist so that class of bug
// fails here rather than in a rendered API table nobody reads closely.

test('extracts a component, its selector, and its members', () => {
  const api = buildApi();
  const checkbox = api['checkbox'];

  assert.ok(checkbox, 'checkbox missing from the generated API');
  const hlm = checkbox.find((c) => c.className === 'HlmCheckbox');
  assert.ok(hlm, 'HlmCheckbox class not found');
  assert.equal(hlm.selector, 'hlm-checkbox');

  const names = hlm.members.map((m) => m.name);
  assert.ok(names.includes('checked'), 'checked input missing');
  assert.ok(names.includes('inputId'), 'inputId input missing');
});

test('prefers the alias over the property name, because that is what a consumer binds', () => {
  const hlm = buildApi()['checkbox'].find((c) => c.className === 'HlmCheckbox')!;
  const names = hlm.members.map((m) => m.name);

  // declared as `userClass = input(..., { alias: 'class' })`
  assert.ok(names.includes('class'), "expected the alias 'class'");
  assert.ok(!names.includes('userClass'), 'leaked the internal property name');
});

test('does not read the NEXT member alias — the bug the first version shipped', () => {
  for (const [slug, classes] of Object.entries(buildApi())) {
    for (const cls of classes) {
      const names = cls.members.map((m) => m.kind + ':' + m.name);
      const dupes = names.filter((n, i) => names.indexOf(n) !== i);
      assert.deepEqual(dupes, [], `${slug}/${cls.className} has duplicate members: ${dupes.join(', ')}`);
    }
  }
});

test('distinguishes inputs, outputs and models', () => {
  const hlm = buildApi()['checkbox'].find((c) => c.className === 'HlmCheckbox')!;
  const kind = (name: string) => hlm.members.find((m) => m.name === name)?.kind;

  assert.equal(kind('checked'), 'input');
  assert.equal(kind('checkedChange'), 'output');
  assert.equal(kind('indeterminate'), 'model');
});

test('marks required inputs as required', () => {
  const api = buildApi();
  const required = Object.values(api)
    .flat()
    .flatMap((c) => c.members)
    .filter((m) => m.required);

  // input.required<T>() is used across the set; if none is detected the flag is dead
  assert.ok(required.length > 0, 'no required member detected anywhere');
});

test('covers the whole vendored set rather than a sample', () => {
  const api = buildApi();
  assert.ok(Object.keys(api).length > 50, `expected the full set, got ${Object.keys(api).length}`);
});

test('renders a file that declares its own generated-ness', () => {
  const out = render({ button: [{ className: 'HlmButton', selector: 'button[hlmBtn]', members: [] }] });

  assert.match(out, /GENERATED by tools\/showcase-api/);
  assert.match(out, /do not edit/i);
  assert.match(out, /HlmButton/);
});
