import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { parsePageRoutes, renderReadme, type PageCapture } from './showcase-shots.ts';

/**
 * These pin the two pure pieces of the generator: parsing page-loaders.ts and
 * rendering the markdown. Both are exercised against small fixtures AND the
 * real page-loaders.ts, the same split showcase-api's tests use — a fixture
 * catches a shape regression precisely, the real file catches drift between
 * the parser and the file it is meant to read.
 */

const fixture = `
export const PAGE_ROUTES = [
  // Actions
  { path: 'button', loadComponent: () => 0 },
  {
    path: 'button-group',
    loadComponent: () => 0,
  },

  // Forms
  { path: 'checkbox', loadComponent: () => 0 },
];
`;

test('parsePageRoutes reads slugs in file order, tagged with their preceding category', () => {
  const entries = parsePageRoutes(fixture);

  assert.deepEqual(entries, [
    { category: 'Actions', slug: 'button' },
    { category: 'Actions', slug: 'button-group' },
    { category: 'Forms', slug: 'checkbox' },
  ]);
});

test('parsePageRoutes reads a multi-line entry, not only a single-line one', () => {
  const entries = parsePageRoutes(fixture);

  assert.ok(entries.some((e) => e.slug === 'button-group'));
});

test('parsePageRoutes ignores a trailing comment on a code line as a category header', () => {
  const src = `
    // Actions
    { path: 'button', loadComponent: () => 0 }, // not a category
    { path: 'toggle', loadComponent: () => 0 },
  `;
  const entries = parsePageRoutes(src);

  assert.deepEqual(
    entries.map((e) => e.category),
    ['Actions', 'Actions'],
  );
});

test('parsePageRoutes against the real page-loaders.ts covers every category, in file order', () => {
  const src = readFileSync(
    join('frontend', 'src', 'app', 'showcase', 'page-loaders.ts'),
    'utf8',
  );
  const entries = parsePageRoutes(src);

  // page-loaders.ts's own doc comment calls itself the only record of which
  // pages exist — this pins the parser to it rather than to a count we typed.
  const categories: string[] = [];
  for (const e of entries) if (!categories.includes(e.category)) categories.push(e.category);

  assert.deepEqual(categories, [
    'Actions',
    'Forms',
    'Menus',
    'Overlays',
    'Navigation',
    'Layout',
    'Data display',
    'Feedback',
    'Patterns',
  ]);
  assert.ok(entries.length > 50, `expected the full page set, got ${entries.length}`);
});

test('parsePageRoutes finds no duplicate slugs in the real file', () => {
  const src = readFileSync(
    join('frontend', 'src', 'app', 'showcase', 'page-loaders.ts'),
    'utf8',
  );
  const slugs = parsePageRoutes(src).map((e) => e.slug);
  const dupes = slugs.filter((s, i) => slugs.indexOf(s) !== i);

  assert.deepEqual(dupes, []);
});

const page = (overrides: Partial<PageCapture> = {}): PageCapture => ({
  category: 'Forms',
  slug: 'checkbox',
  heading: 'Checkbox',
  usages: [{ title: 'Default', note: 'The label is a sibling.' }],
  ...overrides,
});

test('renderReadme states it is generated and names the regenerating command', () => {
  const out = renderReadme([page()], { command: 'npm run showcase:shots', portalSlugs: ['dialog'] });

  assert.match(out, /GENERATED by `tools\/showcase-shots\/showcase-shots\.ts`/);
  assert.match(out, /npm run showcase:shots/);
});

test('renderReadme states the overlay caveat once, naming the given portal slugs', () => {
  const out = renderReadme([page()], {
    command: 'npm run showcase:shots',
    portalSlugs: ['dialog', 'tooltip'],
  });

  assert.match(out, /dialog, tooltip/);
  const occurrences = out.split('portal').length - 1;
  assert.equal(occurrences, 1, 'the portal caveat should appear exactly once');
});

test('renderReadme groups the table of contents by category, in first-seen order', () => {
  const out = renderReadme(
    [
      page({ slug: 'input', heading: 'Input', category: 'Forms' }),
      page({ slug: 'button', heading: 'Button', category: 'Actions' }),
    ],
    { command: 'npm run showcase:shots', portalSlugs: [] },
  );

  const forms = out.indexOf('### Forms');
  const actions = out.indexOf('### Actions');
  assert.ok(forms > 0 && actions > 0);
  assert.ok(forms < actions, 'category order should follow the pages it was given, not be re-sorted');
});

test('renderReadme links the table of contents entry to the section anchor', () => {
  const out = renderReadme([page()], { command: 'npm run showcase:shots', portalSlugs: [] });

  assert.match(out, /\[Checkbox\]\(#checkbox\)/);
  assert.match(out, /<a id="checkbox"><\/a>/);
});

test('renderReadme emits a relative image path so it renders on GitHub', () => {
  const out = renderReadme([page()], { command: 'npm run showcase:shots', portalSlugs: [] });

  assert.match(out, /!\[Checkbox\]\(images\/checkbox\.png\)/);
});

test('renderReadme lists each usage title and note', () => {
  const out = renderReadme(
    [page({ usages: [{ title: 'Default', note: 'A note.' }, { title: 'States', note: null }] })],
    { command: 'npm run showcase:shots', portalSlugs: [] },
  );

  assert.match(out, /\*\*Default\*\* — A note\./);
  assert.match(out, /\*\*States\*\*/);
  assert.doesNotMatch(out.split('**States**')[1]!.split('\n')[0]!, /—/);
});

test('renderReadme handles a page with no usages rather than emitting an empty list', () => {
  const out = renderReadme([page({ usages: [] })], { command: 'npm run showcase:shots', portalSlugs: [] });

  assert.match(out, /No usages on this page\./);
});
