#!/usr/bin/env node
// Jig capability catalog generator.
//
// Walks the source tree, extracts every @capability block (see parse.ts), and
// emits the machine index (.bob/registry/catalog.json) and the agent-readable
// view (.bob/registry/CATALOG.md). Run with --check to fail when either file
// is stale; that is the guarantee the pre-commit and CI gates enforce.
//
// Run `npm run catalog` to regenerate and `npm run catalog:check` in the gates.
// Never hand-edit .bob/registry — annotate the code and regenerate.

import { readdirSync, readFileSync, writeFileSync, mkdirSync, statSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseAnnotations, type CapabilityEntry } from './parse.ts';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const REGISTRY = join(ROOT, '.bob', 'registry');
// Scan the application code only. Build tooling under tools/ is not a "reusable
// unit" a feature-agent discovers and reuses, so it stays out of the catalog.
const SCAN_DIRS = ['frontend', 'services', 'apps'];
const SCAN_EXT = ['.ts', '.tsx', '.rs', '.cs'];
const EXCLUDE = new Set([
  'node_modules', 'dist', 'target', 'bin', 'obj', '.git', '.angular', '.bob',
]);

function walk(dir: string, out: string[] = []): string[] {
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return out; // directory not created yet — fine for an early-phase clone
  }
  for (const e of entries) {
    if (EXCLUDE.has(e.name)) continue;
    const full = join(dir, e.name);
    if (e.isDirectory()) walk(full, out);
    else if (SCAN_EXT.some((x) => e.name.endsWith(x)) && !e.name.endsWith('.test.ts')) {
      out.push(full);
    }
  }
  return out;
}

function collect(): CapabilityEntry[] {
  const files = SCAN_DIRS.flatMap((d) => walk(join(ROOT, d)));
  const entries = files.flatMap((f) =>
    parseAnnotations(readFileSync(f, 'utf8'), relative(ROOT, f)),
  );
  return entries.sort(
    (a, b) => a.capability.localeCompare(b.capability) || a.file.localeCompare(b.file),
  );
}

export function renderJson(entries: CapabilityEntry[]): string {
  return JSON.stringify({ generator: 'tools/catalog', count: entries.length, capabilities: entries }, null, 2) + '\n';
}

export function renderMarkdown(entries: CapabilityEntry[]): string {
  const byArea = new Map<string, CapabilityEntry[]>();
  for (const e of entries) {
    const area = e.capability.split('.')[0];
    (byArea.get(area) ?? byArea.set(area, []).get(area)!).push(e);
  }
  const lines: string[] = [
    '# Jig Capability Catalog',
    '',
    '> GENERATED by `tools/catalog`. Do not hand-edit. Annotate the code (see section 5.1 of the bootstrap prompt) and run `npm run catalog`.',
    '',
    `${entries.length} reusable ${entries.length === 1 ? 'capability' : 'capabilities'} across ${byArea.size} ${byArea.size === 1 ? 'area' : 'areas'}.`,
    '',
  ];
  if (entries.length === 0) {
    lines.push('_No capabilities annotated yet. The first reusable unit that carries a `@capability` block will appear here._', '');
  }
  for (const area of [...byArea.keys()].sort()) {
    lines.push(`## ${area}`, '');
    for (const e of byArea.get(area)!) {
      lines.push(`### \`${e.capability}\` — ${e.symbol} (${e.language})`);
      lines.push(`- **Intent:** ${e.intent}`);
      lines.push(`- **Reuse:** ${e.reuse}`);
      lines.push(`- **Where:** \`${e.file}\`${e.since ? ` · since ${e.since}` : ''}`);
      lines.push('');
    }
  }
  return lines.join('\n');
}

function main() {
  const check = process.argv.includes('--check');
  const entries = collect();
  const json = renderJson(entries);
  const md = renderMarkdown(entries);
  const jsonPath = join(REGISTRY, 'catalog.json');
  const mdPath = join(REGISTRY, 'CATALOG.md');

  if (check) {
    const drift: string[] = [];
    for (const [path, want] of [[jsonPath, json], [mdPath, md]] as const) {
      let have = '';
      try { have = readFileSync(path, 'utf8'); } catch { /* missing counts as drift */ }
      if (have !== want) drift.push(relative(ROOT, path));
    }
    if (drift.length) {
      console.error(`Catalog is stale: ${drift.join(', ')}. Run \`npm run catalog\` and commit.`);
      process.exit(1);
    }
    console.log(`Catalog fresh (${entries.length} capabilities).`);
    return;
  }

  mkdirSync(REGISTRY, { recursive: true });
  writeFileSync(jsonPath, json);
  writeFileSync(mdPath, md);
  console.log(`Wrote catalog: ${entries.length} capabilities → .bob/registry/`);
}

// Only run the CLI when invoked directly, not when imported by a test.
if (process.argv[1] && statSync(process.argv[1]).isFile() &&
    fileURLToPath(import.meta.url) === process.argv[1]) {
  main();
}
